" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.

set hlsearch
set incsearch
set smartcase

if &t_Co > 2 || has("gui_running")
  syntax on
endif
